// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARRViWusUbLJbcfiZ5GmJhb6SyHzyYd1M',
    appId: '1:565457114614:web:23d18f04d50140dc9f63d7',
    messagingSenderId: '565457114614',
    projectId: 'com-ecommerce-app-ui',
    authDomain: 'com-ecommerce-app-ui.firebaseapp.com',
    storageBucket: 'com-ecommerce-app-ui.appspot.com',
    measurementId: 'G-1J0B7EB0D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAaKu3qLGZDBCRA6YLjqrQrE3nTL6C740',
    appId: '1:565457114614:android:20b50f97cdae9b6b9f63d7',
    messagingSenderId: '565457114614',
    projectId: 'com-ecommerce-app-ui',
    storageBucket: 'com-ecommerce-app-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApsmaUj9RHKWx0y1DwMN7TvSrcSoGNceg',
    appId: '1:565457114614:ios:2babf0a402718c8b9f63d7',
    messagingSenderId: '565457114614',
    projectId: 'com-ecommerce-app-ui',
    storageBucket: 'com-ecommerce-app-ui.appspot.com',
    iosClientId: '565457114614-a36aoi2mk1fedh77bs8gvo3nro8ea40n.apps.googleusercontent.com',
    iosBundleId: 'com.bike.ecommerce.ui.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApsmaUj9RHKWx0y1DwMN7TvSrcSoGNceg',
    appId: '1:565457114614:ios:2ada1d8bd94220539f63d7',
    messagingSenderId: '565457114614',
    projectId: 'com-ecommerce-app-ui',
    storageBucket: 'com-ecommerce-app-ui.appspot.com',
    iosClientId: '565457114614-17pd1u6en4t17el3n6g6ih0je7dgqoj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppUi.RunnerTests',
  );
}
